export { default as Home } from './Home'
export { default as DetailCategory } from './DetailCategory'
export { default as Work } from './Work'
export { default as Contact } from './Contact'
export { default as DetailPost } from './DetailPost'
export { default as SearchResult } from './DetailPost'
export { default as TagSearchResult } from './DetailPost'
